# Generated by Django 4.0 on 2021-12-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_alter_servicios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
